apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: rs-1
  labels:
    app: myapp-rs1
spec:
  template:
    metadata:
      name: pod-1
      labels:
        app: myapp-pod-1
    spec:
      containers:
        - name: cont-1
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: myapp-pod-1